### ISSUE TITLE
More reliable wiki host is needed.

### ISSUE THREAD

**Issue by 3ji7ja0jb9c** [gowdy/usbids#1]
http://usb-ids.gowdy.us presently is down.  During past couple years, I observed numerous outages.  Please, Mr Gowdy, will you find a more reliable host for The USB ID Repository?

**Comment by gowdy** [comment]
Something more reliable would cost. It is good for it to be free (well, almost).

**Comment by 3ji7ja0jb9c** [comment]
Could it possibly be hosted by a sponsor of Linux?  Would you accept donations from individuals who depend on The USB ID Repository?
